server:
  port: 8001

#数据库连接
spring:
  datasource:
    mode:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/test_all?serverTimezone=UTC&nullCatalogMeansCurrent=true
      username: root
      password: l1998C12r05
    flowable:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/flowable?serverTimezone=UTC&nullCatalogMeansCurrent=true
      username: root
      password: l1998C12r05
#reids链接
#  redis:
#    port: 6379
#    host: 127.0.0.1
#    password: lcr12345

#flowable
#关闭定时任务
flowable:
  async-executor-activate: true
# 将 databaseSchemaUpdate 设置为true， 当Flowable 发现库与数据库表结构不一致时，会自动将数据库表结构升级值新版本
  database-schema-update: true