server:
  port: 8001

#数据库连接
#spring:
#  datasource:
#    username: root
#    password: l1998C12r05
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/test_all?serverTimezone=UTC&nullCatalogMeansCurrent=true
spring:
  datasource:
    dynamic:
      primary: mode
      datasource:
        mode:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/test_all?serverTimezone=UTC&nullCatalogMeansCurrent=true
          username: root
          password: l1998C12r05
        flowable:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/flowable?serverTimezone=UTC&nullCatalogMeansCurrent=true
          username: root
          password: l1998C12r05
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/**/*Mapper.xml
#reids链接
#  redis:
#    port: 6379
#    host: 127.0.0.1
#    password: lcr12345

#flowable
#关闭定时任务
flowable:
  async-executor-activate: true
# 将 databaseSchemaUpdate 设置为true， 当Flowable 发现库与数据库表结构不一致时，会自动将数据库表结构升级值新版本
  database-schema-update: true

#设置token超时时间(秒)
token:
  expiration-s: 3600

